---
title: "data_wrangling_i"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

# Load a data set

```{r}
## reads in a dataset
## absolute path: goes to one location in one specific context (NEVER)
## relative path: shows you a general path in various contexts (ALWAYS)

#relative path here: . = start wherever you are, want to find this folder
"./datascience1/FAS_litters.csv"

litters_data =  read_csv(file = "./data_import_examples/FAS_litters.csv")

## looking at the data to make sure it worked
print(litters_data)

## viewing data set to see if showing correctly
view(litters_data)

##redoing names of variables in data to clean them
litters_data = janitor::clean_names(litters_data)
litters_data

## use :: to only use one function from a package so you don't have to download the whole thing
```

## Learning Check 1
```{r}
## learning check to import in new dataset (pups data)

pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")

print(pups_data)

view(pups_data)

pups_data = janitor::clean_names(pups_data)
pups_data
```

## Skimr function
```{r}
##Shows you summary statistics and distribution of different values
skimr::skim(pups_data)
```

## Arguments to read
```{r}
## usually the first row of csv is column names, but can check with col_names
## na is a string vector to identify msising values to remove them
##skip function skips rows to read data

## Went in to rename column names
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  skip = 10, col_names = FALSE)
## double is basically saying it's a number and can be a decimal
## integer is just integers

## can specify column types ourselves i.e.:

litters_data = read_csv(
  file = "./data_import_examples/FAS_litters.csv",
    col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer(
    )))

## valid column names dont have spaces, have to have back ticks `` around if you want spaces

```

# Read in excel file

```{r}
##Use readxl package to bring them in! yay!

mlbll_data = read_excel(path = "./data_import_examples/mlb11.xlsx")
mlbll_data

## can specify a range of data in the excel sheet
mlbll_data = read_excel(
  path = "./data_import_examples/mlb11.xlsx",
  range = "A1:D7")

```


